<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>ink</string>
    <key>scopeName</key>
    <string>source.ink</string>
    <key>fileTypes</key>
    <array>
      <string>ink</string>
      <string>ink2</string>
    </array>
    <key>uuid</key>
    <string>a29ac98e-945f-4e6e-87b7-ad099d460683</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#knot</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#stitch</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#choice</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#divert</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#gather</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#logic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#glue</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tag</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#interpolevaluablock</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.ink</string>
            <key>begin</key>
            <string>(/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.ink</string>
            <key>begin</key>
            <string>(\/\/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:^)\s*(INCLUDE)(?:\s*)(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.other.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:^)\s*((VAR)|(LIST))\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.var.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.type.list.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#assignment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:^)\s*(CONST)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.const.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#constAssignment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:^)\s*(EXTERNAL)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.external.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#externalFunctionDeclaration</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>externalFunctionDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>assignment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)\s*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressionIdentifier</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constAssignment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)\s*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tempDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
 ^
 \s*
 (temp)
 \s*
 ([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)
 \s*
 (=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.stitch.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>languageLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*(false|true)\s*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.ink constant.language.boolean.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>numberLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*([0-9]+(\.[0-9]+)?)\s*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>stringLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")\s*</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.ink</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>name</key>
                <string>string.quoted.double.ink</string>
                <key>match</key>
                <string>[\w\s]+</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>label</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.label.ink entity.name.label.ink string.quoted.other.ink</string>
            <key>match</key>
            <string>(\()\s*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*\s*(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.label.begin.ink punctuation.definition.string.begin.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.label.begin.ink punctuation.definition.string.begin.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>glue</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.glue.ink keyword.other.ink</string>
            <key>match</key>
            <string>&lt;&gt;</string>
          </dict>
        </array>
      </dict>
      <key>tag</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>((?&lt;!\\)\#)</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>string.tag.ink string.unquoted.ink</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>choice</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:^)\s*(((\s*[\*]\s*)+)|((\s*[\+]\s*)+))</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.ink keyword.operator.arithmetic.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.sticky.ink keyword.operator.arithmetic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=(^\s*(\-|\*|\+|\=)))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#textSuppression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>choiceInGather</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(((\s*[\*]\s*)+)|((\s*[\+]\s*)+))</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.ink keyword.operator.arithmetic.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.sticky.ink keyword.operator.arithmetic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=(^\s*(\-|\*|\+|\=)))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#textSuppression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>textSuppression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\[)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.suppression.ink keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.suppression.ink keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>logic</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(~)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.logic.ink keyword.operator.arithmetic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>($)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
                <key>match</key>
                <string>return</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
                <key>match</key>
                <string>[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>gather</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*((\s*\-\s*(?!&gt;))+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.gather.ink keyword.operator.arithmetic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choiceInGather</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>knot</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(={2,})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink punctuation.definition.generic.begin.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>((={2,})|(?=^))</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink punctuation.definition.generic.end.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionDeclaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#knotStitchDeclaration</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>stitch</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink punctuation.definition.generic.begin.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#knotStitchDeclaration</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>knotStitchDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))|(?=$)|(?=\=)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)\s*(function)\s*([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))|(?=$)|(?=\=)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionDeclarationParameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>name</key>
                <string>storage.modifier.ref.ink</string>
                <key>match</key>
                <string>ref</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter.function.ink</string>
                <key>match</key>
                <string>[a-zA-Z0-9_]+</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.ink</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*((LIST_COUNT|LIST_MIN|LIST_MAX|LIST_ALL|LIST_INVERT|LIST_RANDOM|CHOICE_COUNT|TURNS_SINCE|LIST_RANGE|TURNS|POW|FLOOR|CEILING|INT|FLOAT)|([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*))\s*(\()\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.language.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.function.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>meta.parens punctuation.section.parens.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.parens punctuation.section.parens.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.ink</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>divert</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(-&gt;|&lt;-)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.divert.ink keyword.other.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\|))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertStitchIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertKnotIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tunnel</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>divertKnotIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*((END|DONE)|([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*))</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.constant.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\|))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tunnel</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>divertStitchIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*((END|DONE)|([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(\.)([a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*))</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.constant.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.stitch.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.ink</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.stitch.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\|))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tunnel</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tunnel</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(-&gt;|&lt;-)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.divert.ink keyword.other.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\|))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertStitchIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertKnotIdentifier</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>interpolevaluablock</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolatedIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#probableExpression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#blockAlternative</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#conditionalExpressionOrfirstAlternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#conditionalElseClauseOrAlternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conditionalIfClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\|)|(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choice</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conditionalElseClauseOrAlternativeItem</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})|(?=\|\s*(?!$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conditionalExpressionOrfirstAlternativeItem</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)(\s*((&amp;|!|~)?(\|))?(&amp;|!|~)?)</string>
            <key>beginCaptures</key>
            <dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.alternative.ink keyword.operator.arithmetic.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.alternative.ink keyword.operator.arithmetic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\|\s*(?!$))|(?=\:\s*(?!$))|(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#colonSuffixed</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#conditionalIfClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>hyphenClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:^)\s*(-)(?!\&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})|(?=^)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenElse</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenExpression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hyphenContent</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>hyphenElse</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*(else)\s*(:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>hyphenExpression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\-)</string>
            <key>end</key>
            <string>(:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>hyphenContent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\:)</string>
            <key>end</key>
            <string>(?=^\s*(\}|(-(?!\&gt;))))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#clauseContent</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>blockAlternative</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)\s*(stopping|shuffle|cycle|once)\s*(:)$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.alternative.ink keyword.operator.arithmetic.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^\s*\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#blockAlternativeItem</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>blockAlternativeItem</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(-)(?!\&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^\s*\})|(?=^\s*\-(?!\&gt;))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>blockIfCondition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=\{)([^\n\r]+)(:)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>blockIfClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)</string>
            <key>end</key>
            <string>(?=^\s*\})|(?=^\s*\-(?!\&gt;))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#blockIfCondition</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#clauseContent</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>clauseContent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#divert</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#logic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glue</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolevaluablock</string>
          </dict>
        </array>
      </dict>
      <key>colonSuffixed</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=\{|\s)([^\{\}\|]+)(:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>probableExpression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=\{)(?&lt;!^)([^\|\{\}\:]+)(?!$)(?=\})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tempDeclaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#languageLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#stringLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressionIdentifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numberLiteral</string>
          </dict>
        </array>
      </dict>
      <key>expressionIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?x)
  ((?&lt;=&amp;&amp;) | (?&lt;=\|\|) |
   (?&lt;=\=) |
   (?&lt;=/)  | (?&lt;=%)    | (?&lt;=\*) | (?&lt;=\+) | (?&lt;=\-) |
   (?&lt;=\?) | (?&lt;=!\?)  | (?&lt;=\^) |
   (?&lt;=,)  | (?=\)))
  \s*
  [a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?x)
  \s*
  ((?&lt;=not) | (?&lt;=and) | (?&lt;=or) | (?&lt;=has) | (?&lt;=hasnt) | (?&lt;=mod))
  [^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]
  [a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?x)
  \s*
  [a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  \s*
  ((?=&amp;&amp;) | (?=\|\|) |
   (?=\=) | (?=!\=)  | (?=\&gt;) | (?=\&lt;) |
   (?=/)  | (?=%)    | (?=\*) | (?=\+) | (?=\-) |
   (?=\?) | (?=!\?)  | (?=\^) |
   (?=,)  | (?=\)))</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?x)
  \s*
  [a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  [^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]
  ((?=not) | (?=and) | (?=or) | (?=has) | (?=hasnt) | (?=mod))</string>
          </dict>
        </array>
      </dict>
      <key>interpolatedIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?&lt;=\{)(?&lt;!^)\s*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*\s*(?!$)(?=\})</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.ink</string>
            <key>match</key>
            <string>(?x)
  !(?!=) |
  &amp;&amp;     |
  \|\|</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ink</string>
            <key>match</key>
            <string>(?x)
  =(?!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.augmented.ink</string>
            <key>match</key>
            <string>(?x)
  %=   |
  &amp;=   |
  \*=  |
  \+=  |
  -=   |
  /=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.relational.ink</string>
            <key>match</key>
            <string>(?x)
  &lt;=   |
  &gt;=   |
  &lt;    |
  &gt;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.ink</string>
            <key>match</key>
            <string>(?x)
  ==   |
  !=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.ink</string>
            <key>match</key>
            <string>(?x)
  --   |
  \+\+ |
  /    |
  %    |
  \*   |
  \+   |
  (?&lt;!\n)\s*-\s*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.membership.ink</string>
            <key>match</key>
            <string>(?x)
  \?  |
  !\? |
  \^</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.word.ink</string>
            <key>match</key>
            <string>(?x)
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])not   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])and   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])or    (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])has   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])hasnt (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])mod   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>