<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>ink</string>
    <key>scopeName</key>
    <string>source.ink</string>
    <key>fileTypes</key>
    <array>
      <string>ink</string>
      <string>ink2</string>
    </array>
    <key>uuid</key>
    <string>a29ac98e-945f-4e6e-87b7-ad099d460683</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tag</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#todo</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#knot</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#stitch</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#choice</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#divert</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#gather</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#logic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#glue</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#interpolevaluablock</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.ink</string>
            <key>begin</key>
            <string>(/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.ink</string>
            <key>begin</key>
            <string>(\/\/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
          </dict>
        </array>
      </dict>
      <key>tag</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.other.ink entity.tag.ink</string>
            <key>begin</key>
            <string>(?&lt;!\\)(\#)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ink comment.line.ink entity.tag.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$|\#)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>todo</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.ink entity.todo.ink</string>
            <key>begin</key>
            <string>(?&lt;=^|\-)(?:[^\S\n\r])*(TODO)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.other entity.todo.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:^)(?:[^\S\n\r])*(INCLUDE)(?:(?:[^\S\n\r])*)(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.other.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:^)(?:[^\S\n\r])*((VAR)|(LIST))(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.var.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.type.list.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:^)(?:[^\S\n\r])*(CONST)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.const.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#constAssignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:^)(?:[^\S\n\r])*(EXTERNAL)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.external.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#externalFunctionDeclaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>externalFunctionDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>assignment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(?:[^\S\n\r])*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressionIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constAssignment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(?:[^\S\n\r])*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.ink entity.name.variable.other.constant.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressionIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tempDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
 (?:(?&lt;=^)|(?&lt;=\~))
 (?:[^\S\n\r])*
 (temp)
 (?:[^\S\n\r])*
 ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)
 (?:[^\S\n\r])*
 (=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.assignment.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressionIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>languageLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:[^\S\n\r])*(false|true)(?:[^\S\n\r])*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.boolean.ink constant.language.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>numberLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:[^\S\n\r])*([0-9]+(\.[0-9]+)?)(?:[^\S\n\r])*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>stringLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r]*)(\")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\")(?:[^\S\n\r]*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.ink</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>name</key>
                <string>string.quoted.double.ink</string>
                <key>match</key>
                <string>[^\n\r\"]+</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>label</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.label.ink entity.name.label.ink string.quoted.other.ink</string>
            <key>match</key>
            <string>(\()(?:[^\S\n\r])*[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*(?:[^\S\n\r])*(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.label.begin.ink punctuation.definition.string.begin.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.label.begin.ink punctuation.definition.string.begin.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>glue</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.glue.ink keyword.other.ink</string>
            <key>match</key>
            <string>&lt;&gt;</string>
          </dict>
        </array>
      </dict>
      <key>choice</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
 (?&lt;=^|\-)
 (?:[^\S\n\r])*
 (?:
   ((?:(?:[^\S\n\r])*[\*])+)
   |
   ((?:(?:[^\S\n\r])*[\+])+)
 )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.sticky.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\#|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inlineConditionalSubstitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#textSuppression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>choiceInClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
 (?&lt;=^|\-|\:)
 (?:[^\S\n\r])*
 (?:
   ((?:(?:[^\S\n\r])*[\*])+)
   |
   ((?:(?:[^\S\n\r])*[\+])+)
 )</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.sticky.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\#|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inlineConditionalSubstitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#textSuppression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>textSuppression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(\[)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.suppression.ink keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\\)(\])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.choice.suppression.ink keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>logic</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:(?&lt;=^)|(?&lt;=\-)|(?&lt;=\:))(?:[^\S\n\r])*(~)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.logic.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#returnStatement</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tempDeclaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>returnStatement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r])*(return)(?=\s)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#function</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressionIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>gather</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=^)(?:[^\S\n\r])*((?:(?:[^\S\n\r])*\-(?!&gt;))+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.gather.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choice</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#label</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#todo</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>knot</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(?:[^\S\n\r])*(={2,})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(={2,})|(?=$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionDeclaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#knotStitchDeclaration</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>stitch</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(?:[^\S\n\r])*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.knot.ink storage.type.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#knotStitchDeclaration</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>knotStitchDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r])*([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))|(?=$|\=|\/\/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionDeclaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)(?:[^\S\n\r])*(function)(?:[^\S\n\r])*([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))|(?=$)|(?=\=)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionDeclarationParameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionDeclarationParameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>name</key>
                <string>storage.modifier.ref.ink</string>
                <key>match</key>
                <string>ref</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter.function.ink</string>
                <key>match</key>
                <string>[a-zA-Z0-9_]+</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.ink</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r])*((LIST_COUNT|LIST_MIN|LIST_MAX|LIST_ALL|LIST_INVERT|LIST_RANDOM|CHOICE_COUNT|TURNS_SINCE|LIST_RANGE|TURNS|POW|FLOOR|CEILING|INT|FLOAT)|([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*))(?:[^\S\n\r])*(\()(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.language.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.function.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.ink</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>divert</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r])*(-&gt;|&lt;-)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.divert.ink keyword.other.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\||\-|\#))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertIdentifier</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tunnel</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>divertIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x) (?:[^\S\n\r])* (?:
  (END|DONE)
  |
  (?:
    ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)
    (?:
      (\.)
      ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)
      (?:
        (\.)
        ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)
      )?
    )?
  )
)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.ink constant.language.divert constant.language.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot.ink entity.name.variable.other.knot.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.ink</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.stitch.ink entity.name.variable.other.stitch.ink</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.ink</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.other.label.ink entity.name.variable.other.label.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\||\#))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tunnel</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tunnel</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:[^\S\n\r])*(-&gt;(?:-&gt;)?|&lt;-)(?:[^\S\n\r])*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.divert.ink keyword.other.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=($|\}|\)|\|))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divertIdentifier</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>interpolevaluablock</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\\)(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#multilineAlternative</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#multilineBlock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#conditionalSubstitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#substitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#firstAlternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#alternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inlineConditionalSubstitution</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\\)(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#conditionalSubstitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#substitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#firstAlternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#alternativeItem</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inlineCondition</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inlineCondition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.ink</string>
            <key>match</key>
            <string>([^\{\}]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>substitution</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=\{)([^\{\}\:\|]+)(?=\})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>firstAlternativeItem</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)(?:[^\S\n\r])*(&amp;|!|~)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink keyword.alternative.type.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\|)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#conditionalSubstitution</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>alternativeItem</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})|(?=\|)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#languageLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numberLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#stringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conditionalSubstitution</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>((?:[^\{\}\|]|\|(?=\|))+(?:[^\S\n\r])*\:)(?:[^\S\n\r])*(?!$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inlineElseClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inlineElseClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>multilineBlock</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([^\{\}]+(?:[^\S\n\r])*\:)(?:[^\S\n\r])*(?=$|\/\/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#caseClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#alternativeClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choice</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#todo</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>multilineAlternative</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)(?:[^\S\n\r])*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#caseClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#alternativeClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choice</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#todo</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>caseClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(?:[^\S\n\r])*(-(?!&gt;))(?:[^\S\n\r])?(else|[^\|\{\}\:]+)(?:[^\S\n\r])*(?&lt;!\\)(\:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^)|(?=\})|(?=\-)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glue</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choiceInClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>alternativeClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(?:[^\S\n\r])*(-(?!&gt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.ink</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^)|(?=\})|(?=\-)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolevaluablock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#divert</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#logic</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#choice</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parentheses</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#languageLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#stringLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressionIdentifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numberLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#commas</string>
          </dict>
        </array>
      </dict>
      <key>parentheses</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin.ink</string>
            <key>match</key>
            <string>\(</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end.ink</string>
            <key>match</key>
            <string>\)</string>
          </dict>
        </array>
      </dict>
      <key>commas</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.separator.ink</string>
            <key>match</key>
            <string>\,</string>
          </dict>
        </array>
      </dict>
      <key>expressionIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?x)
  (?:(?&lt;=return) |
     (?&lt;=&amp;&amp;) | (?&lt;=\|\|) |
     (?&lt;=\=) |
     (?&lt;=/)  | (?&lt;=%)    | (?&lt;=\*) | (?&lt;=\+) | (?&lt;=\-) |
     (?&lt;=\?) | (?&lt;=!\?)  | (?&lt;=\^) | (?&lt;=\~) |
     (?&lt;=,)  | (?=\)))
  (?:[^\S\n\r])*
  ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  (?:\.[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?x)
  (?:[^\S\n\r])*
  (?:(?&lt;=not) | (?&lt;=and) | (?&lt;=or) | (?&lt;=has) | (?&lt;=hasnt) | (?&lt;=mod))
  [^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]
  ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  (?:\.[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?x)
  (?:[^\S\n\r])*
  ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  (?:\.[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)?)
  (?:[^\S\n\r])*
  (?:(?=&amp;&amp;) | (?=\|\|) |
     (?=\=) | (?=!\=)  | (?=\&gt;) | (?=\&lt;) |
     (?=/)  | (?=%)    | (?=\*) | (?=\+) | (?=\-) |
     (?=\?) | (?=!\?)  | (?=\^) |
     (?=,)  | (?=\)))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?x)
  (?:[^\S\n\r])*
  ([a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*
  (?:\.[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)?)
  [^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]
  (?:(?=not) | (?=and) | (?=or) | (?=has) | (?=hasnt) | (?=mod))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.ink</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>interpolatedIdentifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.ink</string>
            <key>match</key>
            <string>(?&lt;=\{)(?&lt;!^)(?:[^\S\n\r])*[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*(\.[a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*[a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}][a-zA-Z0-9_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}]*)?(?:[^\S\n\r])*(?!$)(?=\})</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.ink</string>
            <key>match</key>
            <string>(?x)
  \~     |
  !(?!=) |
  &amp;&amp;     |
  \|\|</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ink</string>
            <key>match</key>
            <string>(?x)
  =(?!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.augmented.ink</string>
            <key>match</key>
            <string>(?x)
  %=  |
  &amp;=  |
  \*= |
  \+= |
  \-= |
  /=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.relational.ink</string>
            <key>match</key>
            <string>(?x)
  &lt;=   |
  &gt;=   |
  &lt;    |
  &gt;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.ink</string>
            <key>match</key>
            <string>(?x)
  ==   |
  !=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.ink</string>
            <key>match</key>
            <string>(?x)
  \-\- |
  \+\+ |
  /    |
  %    |
  \*   |
  \+   |
  (?&lt;!$)(?:[^\S\n\r])*-(?:[^\S\n\r])*(?!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.membership.ink</string>
            <key>match</key>
            <string>(?x)
  \?  |
  !\? |
  \^</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.word.ink</string>
            <key>match</key>
            <string>(?x)
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])not   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])and   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])or    (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])has   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])hasnt (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])   |
  (?&lt;=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])mod   (?=[^a-zA-Z_\x{0100}-\x{017F}\x{0180}-\x{024F}\x{0600}-\x{06FF}\x{0530}-\x{058F}\x{0400}-\x{04FF}\x{0370}-\x{03FF}\x{0590}-\x{05FF}])</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>